webdriver_path: /usr/local/bin/chromedriver

google_api_key: AIzaSyD9QUyVQIkosTVTUo0pBszj_-tEKO36akc

postgreSQL:
    database: realtor
    user: an0nym1ty

searches:
  - 'https://www.wg-gesucht.de/wg-zimmer-in-Hamburg.55.0.0.{page}.html'